package MedicineServicePackage;

/**
* MedicineServicePackage/MedicineHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MedicineService.idl
* wtorek, 14 czerwca 2022 12:41:24 CEST
*/

public final class MedicineHolder implements org.omg.CORBA.portable.Streamable
{
  public MedicineServicePackage.Medicine value = null;

  public MedicineHolder ()
  {
  }

  public MedicineHolder (MedicineServicePackage.Medicine initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MedicineServicePackage.MedicineHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MedicineServicePackage.MedicineHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MedicineServicePackage.MedicineHelper.type ();
  }

}
