package MedicineServicePackage;


/**
* MedicineServicePackage/medicine_listHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MedicineService.idl
* wtorek, 14 czerwca 2022 12:41:24 CEST
*/

public final class medicine_listHolder implements org.omg.CORBA.portable.Streamable
{
  public MedicineServicePackage.Medicine value[] = null;

  public medicine_listHolder ()
  {
  }

  public medicine_listHolder (MedicineServicePackage.Medicine[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MedicineServicePackage.medicine_listHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MedicineServicePackage.medicine_listHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MedicineServicePackage.medicine_listHelper.type ();
  }

}
