package MedicineServicePackage;

/**
* MedicineServicePackage/not_found_exceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MedicineService.idl
* wtorek, 14 czerwca 2022 12:41:24 CEST
*/

public final class not_found_exceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public MedicineServicePackage.not_found_exception value = null;

  public not_found_exceptionHolder ()
  {
  }

  public not_found_exceptionHolder (MedicineServicePackage.not_found_exception initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MedicineServicePackage.not_found_exceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MedicineServicePackage.not_found_exceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MedicineServicePackage.not_found_exceptionHelper.type ();
  }

}
