
/**
* _MedicineServiceImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MedicineService.idl
* wtorek, 14 czerwca 2022 12:41:24 CEST
*/

public abstract class _MedicineServiceImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements MedicineService, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _MedicineServiceImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getMedicines", new java.lang.Integer (0));
    _methods.put ("getMedicineById", new java.lang.Integer (1));
    _methods.put ("addMedicine", new java.lang.Integer (2));
    _methods.put ("getMedicineByName", new java.lang.Integer (3));
    _methods.put ("getMedicineByNameDose", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MedicineService/getMedicines
       {
         MedicineServicePackage.Medicine $result[] = null;
         $result = this.getMedicines ();
         out = $rh.createReply();
         MedicineServicePackage.medicine_listHelper.write (out, $result);
         break;
       }

       case 1:  // MedicineService/getMedicineById
       {
         try {
           int id = in.read_long ();
           MedicineServicePackage.Medicine $result = null;
           $result = this.getMedicineById (id);
           out = $rh.createReply();
           MedicineServicePackage.MedicineHelper.write (out, $result);
         } catch (MedicineServicePackage.not_found_exception $ex) {
           out = $rh.createExceptionReply ();
           MedicineServicePackage.not_found_exceptionHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // MedicineService/addMedicine
       {
         MedicineServicePackage.Medicine med = MedicineServicePackage.MedicineHelper.read (in);
         this.addMedicine (med);
         out = $rh.createReply();
         break;
       }

       case 3:  // MedicineService/getMedicineByName
       {
         try {
           String name = in.read_string ();
           MedicineServicePackage.Medicine $result = null;
           $result = this.getMedicineByName (name);
           out = $rh.createReply();
           MedicineServicePackage.MedicineHelper.write (out, $result);
         } catch (MedicineServicePackage.not_found_exception $ex) {
           out = $rh.createExceptionReply ();
           MedicineServicePackage.not_found_exceptionHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // MedicineService/getMedicineByNameDose
       {
         try {
           String name = in.read_string ();
           double dose = in.read_double ();
           MedicineServicePackage.Medicine $result = null;
           $result = this.getMedicineByNameDose (name, dose);
           out = $rh.createReply();
           MedicineServicePackage.MedicineHelper.write (out, $result);
         } catch (MedicineServicePackage.not_found_exception $ex) {
           out = $rh.createExceptionReply ();
           MedicineServicePackage.not_found_exceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MedicineService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _MedicineServiceImplBase
