
/**
* _MedicineServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MedicineService.idl
* wtorek, 14 czerwca 2022 12:41:24 CEST
*/

public class _MedicineServiceStub extends org.omg.CORBA.portable.ObjectImpl implements MedicineService
{

  public MedicineServicePackage.Medicine[] getMedicines ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMedicines", true);
                $in = _invoke ($out);
                MedicineServicePackage.Medicine $result[] = MedicineServicePackage.medicine_listHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getMedicines (        );
            } finally {
                _releaseReply ($in);
            }
  } // getMedicines

  public MedicineServicePackage.Medicine getMedicineById (int id) throws MedicineServicePackage.not_found_exception
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMedicineById", true);
                $out.write_long (id);
                $in = _invoke ($out);
                MedicineServicePackage.Medicine $result = MedicineServicePackage.MedicineHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:MedicineService/not_found_exception:1.0"))
                    throw MedicineServicePackage.not_found_exceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getMedicineById (id        );
            } finally {
                _releaseReply ($in);
            }
  } // getMedicineById

  public void addMedicine (MedicineServicePackage.Medicine med)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addMedicine", true);
                MedicineServicePackage.MedicineHelper.write ($out, med);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addMedicine (med        );
            } finally {
                _releaseReply ($in);
            }
  } // addMedicine

  public MedicineServicePackage.Medicine getMedicineByName (String name) throws MedicineServicePackage.not_found_exception
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMedicineByName", true);
                $out.write_string (name);
                $in = _invoke ($out);
                MedicineServicePackage.Medicine $result = MedicineServicePackage.MedicineHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:MedicineService/not_found_exception:1.0"))
                    throw MedicineServicePackage.not_found_exceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getMedicineByName (name        );
            } finally {
                _releaseReply ($in);
            }
  } // getMedicineByName

  public MedicineServicePackage.Medicine getMedicineByNameDose (String name, double dose) throws MedicineServicePackage.not_found_exception
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMedicineByNameDose", true);
                $out.write_string (name);
                $out.write_double (dose);
                $in = _invoke ($out);
                MedicineServicePackage.Medicine $result = MedicineServicePackage.MedicineHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:MedicineService/not_found_exception:1.0"))
                    throw MedicineServicePackage.not_found_exceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getMedicineByNameDose (name, dose        );
            } finally {
                _releaseReply ($in);
            }
  } // getMedicineByNameDose

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MedicineService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _MedicineServiceStub
