
/**
* MedicineServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MedicineService.idl
* wtorek, 14 czerwca 2022 12:41:24 CEST
*/

abstract public class MedicineServiceHelper
{
  private static String  _id = "IDL:MedicineService:1.0";

  public static void insert (org.omg.CORBA.Any a, MedicineService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MedicineService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MedicineServiceHelper.id (), "MedicineService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MedicineService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MedicineServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MedicineService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MedicineService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MedicineService)
      return (MedicineService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _MedicineServiceStub stub = new _MedicineServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MedicineService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MedicineService)
      return (MedicineService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _MedicineServiceStub stub = new _MedicineServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
