
/**
* MedicineServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MedicineService.idl
* wtorek, 14 czerwca 2022 12:41:24 CEST
*/

public interface MedicineServiceOperations 
{
  MedicineServicePackage.Medicine[] getMedicines ();
  MedicineServicePackage.Medicine getMedicineById (int id) throws MedicineServicePackage.not_found_exception;
  void addMedicine (MedicineServicePackage.Medicine med);
  MedicineServicePackage.Medicine getMedicineByName (String name) throws MedicineServicePackage.not_found_exception;
  MedicineServicePackage.Medicine getMedicineByNameDose (String name, double dose) throws MedicineServicePackage.not_found_exception;
} // interface MedicineServiceOperations
